<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/OSL-3.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@h-hennes.fr so we can send you a copy immediately.
 *
 * @author    Hennes Hervé <contact@h-hennes.fr>
 * @copyright since 2016 Hennes Hervé
 * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 * https://github.com/nenes25/prestashop_console
 * https://www.h-hennes.fr/blog/
 */

namespace PrestashopConsole\Command\Module\Generate;

class ModuleHeader
{
    /**
     * Get file header for generated modules
     * If .prestashopConsole/licence.txt exists, use it, otherwise use default header
     *
     * @return string
     */
    public static function getHeader()
    {
        $customLicencePath = _PS_ROOT_DIR_ . '/.prestashopConsole/licence.txt';

        if (file_exists($customLicencePath)) {
            return file_get_contents($customLicencePath);
        }

        return self::getDefaultHeader();
    }

    /**
     * Get default header template
     *
     * @return string
     */
    private static function getDefaultHeader()
    {
        return
'/**
 * 2007-' . date('Y') . ' PrestaShop
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 *
 * @author    yourName
 * @copyright 2007-' . date('Y') . ' 
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * 
 * @generated by PrestashopConsole  / copyright 2016-' . date('Y') . ' Hennes Hervé http://www.h-hennes.fr/blog/
 */
 ';
    }
}
