name: Bug report
description: You've got a problem with this module, open a new issue
assignees: nenes25
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using the module and reporting an issue  
        In order to allow us to help you, please fill the following fields
  - type: dropdown
    id: psconsoleversion
    attributes:
      label: PrestashopConsole
      description: Your prestashopConsole version
      multiple: false
      options:
        - 1.6.x
        - 2.0.x
    validations:
      required: true
  - type: dropdown
    id: prestashop_version
    attributes:
      label: Your prestashop version
      description: Wich version of prestashop are you using ( Only currently supported versions are listed )
      multiple: false
      options:
        - < 1.7
        - 1.7.2.x
        - 1.7.3.x
        - 1.7.4.x
        - 1.7.5.x
        - 1.7.6.x
        - 1.7.7.x
        - 1.7.8.x
    validations:
      required: true
  - type: dropdown
    id: php_version
    attributes:
      label: Php Version
      description: Your server php version ( Only currently supported versions are listed )
      multiple: false
      options:
        - 5.6
        - 7.0
        - 7.1
        - 7.2
        - 7.3
        - 7.4
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      placeholder: Add any other context about the problem here.