name: PHP tests
on: [push, pull_request]
jobs:
  php-linter:
    name: PHP Syntax check 7.2|7.3|7.4
    runs-on: ubuntu-latest
    steps:
      - name: PHP syntax checker 7.4
        uses: prestashop/github-action-php-lint/7.4@master
      - name: PHP syntax checker 7.4
        uses: prestashop/github-action-php-lint/7.4@master
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Run PHP-CS-Fixer
        uses: prestashopcorp/github-action-php-cs-fixer@master